import type { FilterData } from "./Types"

// Example filter data - this would be replaced with your actual data
export const defaultFilterData: FilterData = {
  sections: [
    {
      id: "categories",
      title: "CATEGORIES",
      type: "checkbox",
      expanded: true,
      options: [
        {
          id: "bags",
          label: "Bags",
          count: 26600,
          value: "bags",
          checked: false,
        },
        {
          id: "accessories",
          label: "Accessories",
          count: 1743,
          value: "accessories",
          checked: false,
        },
        {
          id: "shoes",
          label: "Shoes",
          count: 1555,
          value: "shoes",
          checked: false,
        },
        {
          id: "jewelry",
          label: "Jewelry",
          count: 1334,
          value: "jewelry",
          checked: false,
        },
        {
          id: "watches",
          label: "Watches",
          count: 346,
          value: "watches",
          checked: false,
        },
        {
          id: "apparel",
          label: "Apparel",
          count: 1743,
          value: "apparel",
          checked: false,
        },
      ],
    },
    {
      id: "bagType",
      title: "BAG TYPE",
      type: "checkbox",
      expanded: false,
      options: [
        {
          id: "shoulder-bags",
          label: "Shoulder bags",
          count: 9982,
          value: "shoulder-bags",
          checked: false,
        },
        {
          id: "cross-body-bags",
          label: "Cross body bags",
          count: 7864,
          value: "cross-body-bags",
          checked: false,
        },
        {
          id: "totes",
          label: "Totes",
          count: 5291,
          value: "totes",
          checked: false,
        },
        {
          id: "top-handle",
          label: "Top Handle",
          count: 4115,
          value: "top-handle",
          checked: false,
        },
        {
          id: "clutches",
          label: "Clutches",
          count: 1671,
          value: "clutches",
          checked: false,
        },
        {
          id: "hobos",
          label: "Hobos",
          count: 1278,
          value: "hobos",
          checked: false,
        },
        {
          id: "satchels",
          label: "Satchels",
          count: 917,
          value: "satchels",
          checked: false,
        },
        {
          id: "messenger",
          label: "Messenger",
          count: 861,
          value: "messenger",
          checked: false,
        },
        {
          id: "backpacks",
          label: "Backpacks",
          count: 770,
          value: "backpacks",
          checked: false,
        },
        {
          id: "bucket",
          label: "Bucket",
          count: 710,
          value: "bucket",
          checked: false,
        },
      ],
    },
    {
      id: "designers",
      title: "DESIGNERS",
      type: "checkbox",
      expanded: false,
      searchable: true,
      options: [
        {
          id: "louis-vuitton",
          label: "Louis Vuitton",
          count: 9267,
          value: "louis-vuitton",
          checked: false,
        },
        {
          id: "chanel",
          label: "Chanel",
          count: 5463,
          value: "chanel",
          checked: false,
        },
        {
          id: "gucci",
          label: "Gucci",
          count: 4021,
          value: "gucci",
          checked: false,
        },
        {
          id: "hermes",
          label: "Hermes",
          count: 2060,
          value: "hermes",
          checked: false,
        },
        {
          id: "christian-dior",
          label: "Christian Dior",
          count: 1490,
          value: "christian-dior",
          checked: false,
        },
        {
          id: "saint-laurent",
          label: "SaintLaurent",
          count: 1451,
          value: "saint-laurent",
          checked: false,
        },
        {
          id: "prada",
          label: "Prada",
          count: 1149,
          value: "prada",
          checked: false,
        },
        {
          id: "fendi",
          label: "Fendi",
          count: 902,
          value: "Fendi",
          checked: false,
        },
        {
          id: "celine",
          label: "Celine",
          count: 863,
          value: "celine",
          checked: false,
        },
        {
          id: "govard",
          label: "Govard",
          count: 795,
          value: "govard",
          checked: false,
        },
        {
          id: "bottega-veneta",
          label: "Bottega Veneta",
          count: 578,
          value: "bottega-veneta",
          checked: false,
        },
        {
          id: "cartier",
          label: "Cartier",
          count: 577,
          value: "cartier",
          checked: false,
        },
        {
          id: "valentino-garavani",
          label: "Valentino Garavani",
          count: 376,
          value: "valentino-garavani",
          checked: false,
        },
        {
          id: "balenciaga",
          label: "Balenciaga",
          count: 374,
          value: "balenciaga",
          checked: false,
        },
        {
          id: "christian-louboutin",
          label: "Christian Louboutin",
          count: 275,
          value: "christian-louboutin",
          checked: false,
        },
        {
          id: "chloe",
          label: "Chloe",
          count: 266,
          value: "chloe",
          checked: false,
        },
        {
          id: "burberry",
          label: "Burberry",
          count: 577,
          value: "burberry",
          checked: false,
        },
        {
          id: "van-cleef-&-arpels",
          label: "Van Cleef & Arpels",
          count: 376,
          value: "van-cleef-&-arpels",
          checked: false,
        },
        {
          id: "tiffany-&-co",
          label: "Tiffany & Co",
          count: 374,
          value: "tiffany-&-co.",
          checked: false,
        },
        {
          id: "loewe",
          label: "Loewe",
          count: 275,
          value: "loewe",
          checked: false,
        },
        {
          id: "bvlgari",
          label: "Bvlgari",
          count: 266,
          value: "bvlgari",
          checked: false,
        },
        {
          id: "givenchy",
          label: "givenchy",
          count: 159,
          value: "givenchy",
          checked: false,
        },
        {
          id: "rolex",
          label: "Rolex",
          count: 95,
          value: "rolex",
          checked: false,
        },
        {
          id: "salvatore-ferragamo",
          label: "Salvatore Ferragamo",
          count: 80,
          value: "salvatore-ferragamo",
          checked: false,
        },
        {
          id: "versace",
          label: "Versace",
          count: 57,
          value: "versace",
          checked: false,
        },
        {
          id: "jacquemus",
          label: "Jacquemus",
          count: 47,
          value: "jacquemus",
          checked: false,
        },
        {
          id: "alexander-mcqueen",
          label: "Alexander McQueen",
          count: 38,
          value: "alexander-mcqueen",
          checked: false,
        },
        {
          id: "omega",
          label: "Omega",
          count: 25,
          value: "omega",
          checked: false,
        },
        {
          id: "dolce-&-gabbana",
          label: "Dolce & Gabbana",
          count: 23,
          value: "dolce-&-gabbana",
          checked: false,
        },
        {
          id: "the-low",
          label: "The Low",
          count: 23,
          value: "the-low",
          checked: false,
        },
        {
          id: "amina-muaddi",
          label: "Amina Muaddi",
          count: 22,
          value: "amina-muaddi",
          checked: false,
        },
        {
          id: "tom-ford",
          label: "Tom Ford",
          count: 22,
          value: "tom-ford",
          checked: false,
        },
        {
          id: "breitling",
          label: "Breitling",
          count: 16,
          value: "breitling",
          checked: false,
        },
        {
          id: "off-white",
          label: "Off White",
          count: 16,
          value: "off-white",
          checked: false,
        },
        {
          id: "manolo-blanco",
          label: "Manolo Blanco",
          count: 15,
          value: "manolo-blanco",
          checked: false,
        },
        {
          id: "tag-heuer",
          label: "Tag Heuer",
          count: 14,
          value: "tag-heuer",
          checked: false,
        },
        {
          id: "delvaux",
          label: "Delvaux",
          count: 13,
          value: "delvaux",
          checked: false,
        },
        {
          id: "moncler",
          label: "Moncler",
          count: 11,
          value: "moncler",
          checked: false,
        },
        {
          id: "balmain",
          label: "Balmain",
          count: 10,
          value: "balmain",
          checked: false,
        },
        {
          id: "stella-mccartney",
          label: "Stella McCartney",
          count: 10,
          value: "stella-mccartney",
          checked: false,
        },
        {
          id: "mach-mach",
          label: "Mach Mach",
          count: 9,
          value: "mach-mach",
          checked: false,
        },
        {
          id: "alaia",
          label: "Alaia",
          count: 7,
          value: "alaia",
          checked: false,
        },
        {
          id: "max-mara",
          label: "Max Mara",
          count: 7,
          value: "max-mara",
          checked: false,
        },
        {
          id: "chopard",
          label: "Chopard",
          count: 6,
          value: "chopard",
          checked: false,
        },
        {
          id: "david-yurman",
          label: "David Yurman",
          count: 5,
          value: "david-yurman",
          checked: false,
        },
        {
          id: "miu-miu",
          label: "Miu Miu",
          count: 5,
          value: "miu-miu",
          checked: false,
        },
        {
          id: "tudor",
          label: "Tudor",
          count: 5,
          value: "tudor",
          checked: false,
        },
        {
          id: "canada-goose",
          label: "Canada Goose",
          count: 4,
          value: "canada-goose",
          checked: false,
        },
        {
          id: "plaget",
          label: "Plaget",
          count: 4,
          value: "plaget",
          checked: false,
        },
        {
          id: "thom-browne",
          label: "Thom Browne",
          count: 4,
          value: "thom-browne",
          checked: false,
        },
        {
          id: "chaumet",
          label: "Chaumet",
          count: 3,
          value: "chaumet",
          checked: false,
        },
      ],
    },
    {
      id: "price",
      title: "PRICE",
      type: "range",
      expanded: false,
      options: [
        {
          id: "under-1000",
          label: "Under $1,000",
          count: 9557,
          value: "under-1000",
          checked: false,
        },
        {
          id: "$1000-to-$2000",
          label: "$1000 to $2000",
          count: 14477,
          value: "$1000-to-$2000",
          checked: false,
        },
        {
          id: "$2500-to-$5000",
          label: "$2500 to $5000",
          count: 6313,
          value: "$2500-to-$5000",
          checked: false,
        },
        {
          id: "$5000-to-$10000",
          label: "$5000 to $10000",
          count: 1390,
          value: "$5000-to-$10000",
          checked: false,
        },
        {
          id: "over-10000",
          label: "Over $10000",
          count: 650,
          value: "over-10000",
          checked: false,
        },
      ],
    },
    {
      id: "condition",
      title: "CONDITION",
      type: "checkbox",
      expanded: false,
      options: [
        {
          id: "excellent",
          label: "Excellent",
          count: 2611,
          value: "excellent",
          checked: false,
        },
        {
          id: "great",
          label: "Great",
          count: 11681,
          value: "great",
          checked: false,
        },
        {
          id: "very-good",
          label: "Very Good",
          count: 11681,
          value: "very-good",
          checked: false,
        },
        {
          id: "good",
          label: "Good",
          count: 4592,
          value: "good",
          checked: false,
        },
        {
          id: "fair",
          label: "Fair",
          count: 1356,
          value: "fair",
          checked: false,
        },
      ],
    },
    {
      id: "color",
      title: "COLOR",
      type: "checkbox",
      expanded: false,
      options: [
        {
          id: "black",
          label: "Black",
          count: 8785,
          value: "black",
          checked: false,
        },
        {
          id: "brown",
          label: "Brown",
          count: 7888,
          value: "brown",
          checked: false,
        },
        {
          id: "blue",
          label: "Blue",
          count: 3241,
          value: "blue",
          checked: false,
        },
        {
          id: "neutral",
          label: "Neutral",
          count: 2888,
          value: "neutral",
          checked: false,
        },
        {
          id: "red",
          label: "Red",
          count: 2517,
          value: "red",
          checked: false,
        },
      ],
    },
    {
      id: "stores",
      title: "STORES",
      type: "checkbox",
      expanded: false,
      options: [],
    },
    {
      id: "collections",
      title: "COLLECTIONS",
      type: "checkbox",
      expanded: false,
      options: [
        {
          id: "mens-styles",
          label: "Men's Styles",
          count: 1515,
          value: "mens-styles",
          checked: false,
        },
        {
          id: "vintage",
          label: "Vintage",
          count: 379,
          value: "vintage",
          checked: false,
        },
        {
          id: "clair-picks",
          label: "Clair Picks",
          count: 142,
          value: "clair-picks",
          checked: false,
        },
      ],
    },
    {
      id: "material",
      title: "MATERIAL",
      type: "checkbox",
      expanded: false,
      searchable: true,
      options: [
        {
          id: "leather",
          label: "Leather",
          count: 17754,
          value: "leather",
          checked: false,
        },
        {
          id: "canvas-coated",
          label: "Canvas Coated",
          count: 8359,
          value: "canvas-coated",
          checked: false,
        },
        {
          id: "canvas-plain",
          label: "Canvas Plain",
          count: 1588,
          value: "canvas-plain",
          checked: false,
        },
        {
          id: "patent-leather",
          label: "Patent Leather",
          count: 931,
          value: "patent-leather",
          checked: false,
        },
        {
          id: "18k-yellow-gold",
          label: "18K Yellow Gold",
          count: 467,
          value: "18k-yellow-gold",
          checked: false,
        },
        {
          id: "18k-rose-gold",
          label: "18K Rose Gold",
          count: 433,
          value: "18k-rose-gold",
          checked: false,
        },
        {
          id: "nylon",
          label: "Nylon",
          count: 372,
          value: "nylon",
          checked: false,
        },
        {
          id: "denim",
          label: "Denim",
          count: 331,
          value: "denim",
          checked: false,
        },
        {
          id: "suede",
          label: "Suede",
          count: 326,
          value: "suede",
          checked: false,
        },
        {
          id: "stainless-steel",
          label: "Stainless Steel",
          count: 290,
          value: "stainless-steel",
          checked: false,
        },
      ],
    },
    {
      id: "offRetail",
      title: "% OFF RETAIL",
      type: "checkbox",
      expanded: false,
      options: [],
    },
  ],
}

